spring:
  datasource:
    url:  jdbc:mysql://${YATA_MYSQL_HOST}:${YATA_MYSQL_PORT}/${YATA_DATA_BASE_NAME}?useSSL=false
    #jdbc:mysql://localhost:3306/test
    username: ${YATA_MYSQL_USER_NAME}
    password: ${YATA_MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # (1) ??? ?? ??
    show-sql: false      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: ${YATA_REDIS_HOST}
    port: ${YATA_REDIS_PORT}

admin:
  email: ${ADMIN1_EMAIL},${ADMIN2_EMAIL}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}